export type Sale = {
  id: string;
  address: string;
  postcode: string;
  municipality: string;
  municipalityName: string;
  heinum: string;
  propertyId: string;
  date: string;
  registered: string | null;
  year: number;
  month: string;
  price: number;
  valuation: number | null;
  area: number;
  rooms: number | null;
  built: number | null;
  age: number | null;
  type: "apartment" | "house" | "other";
  residential: boolean;
  capital: boolean;
  usable: boolean;
  reasons: string[];
  warnings: string[];
  ppm: number;
  coordinates: [number, number] | null;
  coordinateQuality: string;
  district: string | null;
};
export type Filters = {
  months: number;
  from?: string;
  to?: string;
  type: string;
  municipality: string;
  postcode: string;
  district: string;
  minArea: number;
  maxArea: number;
  rooms: number;
  minBuilt: number;
  maxBuilt: number;
  q: string;
};
export type Stats = {
  count: number;
  ppm: number | null;
  price: number | null;
  area: number | null;
  rooms: number | null;
  built: number | null;
  valuation: number | null;
  ratio: number | null;
  ratioCount: number;
  sparse: boolean;
  change: number | null;
  previousCount: number;
};
export type AreaStats = Stats & {
  id: string;
  name: string;
  kind: "district" | "postcode" | "municipality";
};
export type Exploration = {
  summary: Stats;
  areas: AreaStats[];
  postcodes: AreaStats[];
  municipalities: AreaStats[];
  trend: ({ month: string } & Stats)[];
  recent: Sale[];
  points: GeoJSON.FeatureCollection;
  pointCount: number;
  pointLimit: number;
  from: string;
  to: string;
  downloadedAt: string;
  latestSale: string;
  latestRegistration: string;
  matchedCount: number;
  total: number;
};
